/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Marisol
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        lbl_Error.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        img_logo = new javax.swing.JLabel();
        lbl_iniciarSesion = new javax.swing.JLabel();
        lbl_legajo = new javax.swing.JLabel();
        lbl_contraseña = new javax.swing.JLabel();
        txt_legajo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_problemas = new javax.swing.JLabel();
        lbl_restablecer = new javax.swing.JLabel();
        lbl_Error = new javax.swing.JLabel();
        btn_ingresar = new javax.swing.JButton();
        txt_contraseña = new javax.swing.JPasswordField();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo pequeño.png"))); // NOI18N
        background.add(img_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 69));

        lbl_iniciarSesion.setFont(new java.awt.Font("Roboto Black", 0, 20)); // NOI18N
        lbl_iniciarSesion.setText("INICIAR SESIÓN");
        background.add(lbl_iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        lbl_legajo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbl_legajo.setText("Legajo");
        background.add(lbl_legajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        lbl_contraseña.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbl_contraseña.setText("Contraseña");
        background.add(lbl_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        txt_legajo.setForeground(new java.awt.Color(153, 153, 153));
        txt_legajo.setText("Ingrese su legajo...");
        txt_legajo.setBorder(null);
        txt_legajo.setMargin(new java.awt.Insets(3, 2, 2, 2));
        txt_legajo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_legajoMouseClicked(evt);
            }
        });
        txt_legajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_legajoActionPerformed(evt);
            }
        });
        background.add(txt_legajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 160, 30));

        jSeparator1.setForeground(new java.awt.Color(243, 234, 232));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 160, 20));

        jSeparator2.setForeground(new java.awt.Color(243, 234, 232));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 160, 20));

        lbl_problemas.setFont(new java.awt.Font("Roboto Light", 0, 11)); // NOI18N
        lbl_problemas.setText("¿Problemas al ingresar?");
        background.add(lbl_problemas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        lbl_restablecer.setFont(new java.awt.Font("Roboto Light", 1, 11)); // NOI18N
        lbl_restablecer.setForeground(new java.awt.Color(132, 119, 112));
        lbl_restablecer.setText("Restablecer contraseña");
        lbl_restablecer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lbl_restablecer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_restablecerMouseClicked(evt);
            }
        });
        background.add(lbl_restablecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, -1));

        lbl_Error.setForeground(new java.awt.Color(204, 0, 0));
        lbl_Error.setText("mensaje");
        background.add(lbl_Error, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 210, -1));

        btn_ingresar.setBackground(new java.awt.Color(231, 197, 59));
        btn_ingresar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btn_ingresar.setText("Ingresar");
        btn_ingresar.setBorder(null);
        background.add(btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 120, 30));

        txt_contraseña.setForeground(new java.awt.Color(153, 153, 153));
        txt_contraseña.setText("jPasswordField1");
        txt_contraseña.setBorder(null);
        background.add(txt_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 170, 30));

        btn_salir.setBackground(new java.awt.Color(255, 255, 255));
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconSalir.png"))); // NOI18N
        btn_salir.setBorder(null);
        btn_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_salir.setFocusable(false);
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        background.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 40, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_legajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_legajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_legajoActionPerformed

    private void lbl_restablecerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_restablecerMouseClicked
        RestablecerContraseña view = new RestablecerContraseña();
        this.setVisible(false);
        view.setVisible(true);
    }//GEN-LAST:event_lbl_restablecerMouseClicked

    private void txt_legajoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_legajoMouseClicked
        txt_legajo.setText("");
    }//GEN-LAST:event_txt_legajoMouseClicked

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel img_logo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_Error;
    private javax.swing.JLabel lbl_contraseña;
    private javax.swing.JLabel lbl_iniciarSesion;
    private javax.swing.JLabel lbl_legajo;
    private javax.swing.JLabel lbl_problemas;
    private javax.swing.JLabel lbl_restablecer;
    private javax.swing.JPasswordField txt_contraseña;
    private javax.swing.JTextField txt_legajo;
    // End of variables declaration//GEN-END:variables
}
