/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Marisol
 */
public class ListarClientes extends javax.swing.JPanel {

    /**
     * Creates new form ListarClientes
     */
    public ListarClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bgCuit = new javax.swing.JPanel();
        lbl_estado = new javax.swing.JLabel();
        txt_busqueda = new javax.swing.JTextField();
        lbl_busqueda = new javax.swing.JLabel();
        cb_estado = new javax.swing.JComboBox<>();
        btn_darBaja = new javax.swing.JButton();
        btn_nuevocliente = new javax.swing.JButton();
        btn_editarform = new javax.swing.JButton();
        lbl_infoUsuario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_clientes = new javax.swing.JTable();
        bgBienvenida1 = new javax.swing.JPanel();
        lbl_bienvenida1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgCuit.setBackground(new java.awt.Color(231, 197, 59));
        bgCuit.setForeground(new java.awt.Color(255, 255, 255));
        bgCuit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_estado.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        lbl_estado.setText("Estado");
        bgCuit.add(lbl_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        txt_busqueda.setBorder(null);
        txt_busqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_busquedaMouseClicked(evt);
            }
        });
        bgCuit.add(txt_busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 390, 20));

        lbl_busqueda.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        lbl_busqueda.setText("CUIT o Razon social");
        bgCuit.add(lbl_busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        lbl_busqueda.getAccessibleContext().setAccessibleName("CUIT o Razon social");

        cb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bgCuit.add(cb_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 100, -1));

        btn_darBaja.setBackground(new java.awt.Color(231, 197, 59));
        btn_darBaja.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btn_darBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconBaja.png"))); // NOI18N
        btn_darBaja.setText("Dar de baja");
        btn_darBaja.setBorder(null);
        bgCuit.add(btn_darBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 120, 40));

        btn_nuevocliente.setBackground(new java.awt.Color(231, 197, 59));
        btn_nuevocliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btn_nuevocliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconNuevo.png"))); // NOI18N
        btn_nuevocliente.setText("Nuevo cliente");
        btn_nuevocliente.setBorder(null);
        btn_nuevocliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoclienteActionPerformed(evt);
            }
        });
        bgCuit.add(btn_nuevocliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 150, 30));

        btn_editarform.setBackground(new java.awt.Color(231, 197, 59));
        btn_editarform.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btn_editarform.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconEditar.png"))); // NOI18N
        btn_editarform.setText("Editar datos del cliente");
        btn_editarform.setBorder(null);
        btn_editarform.setBorderPainted(false);
        btn_editarform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarformActionPerformed(evt);
            }
        });
        bgCuit.add(btn_editarform, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 190, -1));

        jPanel1.add(bgCuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 830, 100));

        lbl_infoUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbl_infoUsuario.setText("Usuario: Nombre y apellido empleado - Rol: Administrador");
        jPanel1.add(lbl_infoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        tabla_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CUIT", "Razon social", "telefono", "Correo electrónico", "Domicilio ", "Localidad", "Provincia", "Pais"
            }
        ));
        jScrollPane1.setViewportView(tabla_clientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 810, 440));

        bgBienvenida1.setBackground(new java.awt.Color(0, 0, 0));
        bgBienvenida1.setForeground(new java.awt.Color(255, 255, 255));
        bgBienvenida1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_bienvenida1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        lbl_bienvenida1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_bienvenida1.setText("Lista de clientes");
        bgBienvenida1.add(lbl_bienvenida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel1.add(bgBienvenida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 830, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_busquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_busquedaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_busquedaMouseClicked

    private void btn_nuevoclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nuevoclienteActionPerformed

    private void btn_editarformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarformActionPerformed

    }//GEN-LAST:event_btn_editarformActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgBienvenida1;
    private javax.swing.JPanel bgCuit;
    private javax.swing.JButton btn_darBaja;
    private javax.swing.JButton btn_editarform;
    private javax.swing.JButton btn_nuevocliente;
    private javax.swing.JComboBox<String> cb_estado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_bienvenida1;
    private javax.swing.JLabel lbl_busqueda;
    private javax.swing.JLabel lbl_estado;
    private javax.swing.JLabel lbl_infoUsuario;
    private javax.swing.JTable tabla_clientes;
    private javax.swing.JTextField txt_busqueda;
    // End of variables declaration//GEN-END:variables
}
