/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Marisol
 */
public class NuevoProyecto extends javax.swing.JFrame {

    /**
     * Creates new form NuevoProyecto
     */
    public NuevoProyecto() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        lbl_nuevoproy = new javax.swing.JLabel();
        lbl_nombreproy = new javax.swing.JLabel();
        txt_descriproy = new javax.swing.JTextField();
        lbl_saldoDeuda = new javax.swing.JLabel();
        lbl_horasempleadas = new javax.swing.JLabel();
        txt_nombreProy = new javax.swing.JTextField();
        txt_horasempleadas = new javax.swing.JTextField();
        txt_saldoadeudado = new javax.swing.JTextField();
        cb_estadoproy = new javax.swing.JComboBox<>();
        lbl_fechaInicio = new javax.swing.JLabel();
        lbl_estadoProy = new javax.swing.JLabel();
        lbl_descripProy = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_equipo = new javax.swing.JTable();
        txt_fechaInicio = new javax.swing.JFormattedTextField();
        lbl_detalleEquipo = new javax.swing.JLabel();
        cb_nroEquipo = new javax.swing.JComboBox<>();
        btn_cancelar = new javax.swing.JButton();
        btn_crearProy = new javax.swing.JButton();
        btn_nuevoequipo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(241, 232, 118));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nuevoproy.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbl_nuevoproy.setText("NUEVO PROYECTO");
        bg.add(lbl_nuevoproy, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lbl_nombreproy.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lbl_nombreproy.setText("Nombre");
        bg.add(lbl_nombreproy, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        txt_descriproy.setBorder(null);
        bg.add(txt_descriproy, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 250, 20));

        lbl_saldoDeuda.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lbl_saldoDeuda.setText("Saldo Adeudado");
        bg.add(lbl_saldoDeuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        lbl_horasempleadas.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lbl_horasempleadas.setText("Horas Empleadas");
        bg.add(lbl_horasempleadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        txt_nombreProy.setBorder(null);
        bg.add(txt_nombreProy, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 160, 20));

        txt_horasempleadas.setBorder(null);
        bg.add(txt_horasempleadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 110, 20));

        txt_saldoadeudado.setBorder(null);
        bg.add(txt_saldoadeudado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 110, 20));

        cb_estadoproy.setEditable(true);
        cb_estadoproy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_estadoproy.setBorder(null);
        bg.add(cb_estadoproy, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 100, -1));

        lbl_fechaInicio.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lbl_fechaInicio.setText("Fecha de Inicio");
        bg.add(lbl_fechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        lbl_estadoProy.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lbl_estadoProy.setText("Estado");
        bg.add(lbl_estadoProy, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        lbl_descripProy.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        lbl_descripProy.setText("Descripción");
        bg.add(lbl_descripProy, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        tabla_equipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre y apellido", "Rol"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_equipo.setEnabled(false);
        jScrollPane2.setViewportView(tabla_equipo);

        bg.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 470, 100));

        txt_fechaInicio.setBorder(null);
        bg.add(txt_fechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 120, 20));

        lbl_detalleEquipo.setBackground(new java.awt.Color(204, 0, 0));
        lbl_detalleEquipo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lbl_detalleEquipo.setText("Numero de equipo");
        bg.add(lbl_detalleEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        cb_nroEquipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_nroEquipo.setBorder(null);
        bg.add(cb_nroEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 100, -1));

        btn_cancelar.setBackground(new java.awt.Color(255, 0, 0));
        btn_cancelar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconCancel.png"))); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setBorder(null);
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        bg.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 150, 40));

        btn_crearProy.setBackground(new java.awt.Color(102, 153, 0));
        btn_crearProy.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_crearProy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconCheck.png"))); // NOI18N
        btn_crearProy.setText("Añadir Proyecto");
        btn_crearProy.setBorder(null);
        btn_crearProy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearProyActionPerformed(evt);
            }
        });
        bg.add(btn_crearProy, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 190, 40));

        btn_nuevoequipo.setBackground(new java.awt.Color(231, 197, 59));
        btn_nuevoequipo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btn_nuevoequipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconNuevo.png"))); // NOI18N
        btn_nuevoequipo.setText("Nuevo equipo");
        btn_nuevoequipo.setBorder(null);
        btn_nuevoequipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoequipoActionPerformed(evt);
            }
        });
        bg.add(btn_nuevoequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 253, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_crearProyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearProyActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_crearProyActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
       this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_nuevoequipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoequipoActionPerformed
        NuevoEquipo view= new NuevoEquipo();
        view.setVisible(true);
    }//GEN-LAST:event_btn_nuevoequipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoProyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_crearProy;
    private javax.swing.JButton btn_nuevoequipo;
    private javax.swing.JComboBox<String> cb_estadoproy;
    private javax.swing.JComboBox<String> cb_nroEquipo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_descripProy;
    private javax.swing.JLabel lbl_detalleEquipo;
    private javax.swing.JLabel lbl_estadoProy;
    private javax.swing.JLabel lbl_fechaInicio;
    private javax.swing.JLabel lbl_horasempleadas;
    private javax.swing.JLabel lbl_nombreproy;
    private javax.swing.JLabel lbl_nuevoproy;
    private javax.swing.JLabel lbl_saldoDeuda;
    private javax.swing.JTable tabla_equipo;
    private javax.swing.JTextField txt_descriproy;
    private javax.swing.JFormattedTextField txt_fechaInicio;
    private javax.swing.JTextField txt_horasempleadas;
    private javax.swing.JTextField txt_nombreProy;
    private javax.swing.JTextField txt_saldoadeudado;
    // End of variables declaration//GEN-END:variables
}
