/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Marisol
 */
public class NuevaFactura extends javax.swing.JFrame {

    /**
     * Creates new form NuevaFactura
     */
    public NuevaFactura() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_nuevaFac = new javax.swing.JPanel();
        bg_detalles = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_detallesFac = new javax.swing.JTable();
        lbl_detalleFac = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();
        btn_emitirFac = new javax.swing.JButton();
        lbl_canths = new javax.swing.JLabel();
        txt_hsPagar = new javax.swing.JTextField();
        btn_agregarDetalle = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_proyectos = new javax.swing.JTable();
        lbl_nuevaFac = new javax.swing.JLabel();
        btn_selecProyecto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_nuevaFac.setBackground(new java.awt.Color(255, 255, 255));
        bg_nuevaFac.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_detalles.setBackground(new java.awt.Color(0, 0, 0));
        bg_detalles.setForeground(new java.awt.Color(255, 255, 255));
        bg_detalles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_detallesFac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Proyecto", "Horas", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_detallesFac);

        bg_detalles.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 320, 130));

        lbl_detalleFac.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lbl_detalleFac.setForeground(new java.awt.Color(255, 255, 255));
        lbl_detalleFac.setText("Detalles de la factura");
        bg_detalles.add(lbl_detalleFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btn_cancelar.setBackground(new java.awt.Color(255, 0, 0));
        btn_cancelar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconCancel.png"))); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setBorder(null);
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        bg_detalles.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, 40));

        btn_emitirFac.setBackground(new java.awt.Color(102, 153, 0));
        btn_emitirFac.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_emitirFac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconEnviar.png"))); // NOI18N
        btn_emitirFac.setText("EMITIR FACTURA");
        btn_emitirFac.setBorder(null);
        btn_emitirFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_emitirFacActionPerformed(evt);
            }
        });
        bg_detalles.add(btn_emitirFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 210, 50));

        lbl_canths.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbl_canths.setForeground(new java.awt.Color(255, 255, 255));
        lbl_canths.setText("Cantidad de horas a pagar:");
        bg_detalles.add(lbl_canths, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        txt_hsPagar.setBorder(null);
        txt_hsPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hsPagarActionPerformed(evt);
            }
        });
        bg_detalles.add(txt_hsPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 70, 20));

        btn_agregarDetalle.setBackground(new java.awt.Color(132, 119, 112));
        btn_agregarDetalle.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btn_agregarDetalle.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregarDetalle.setText("Agregar a detalle");
        btn_agregarDetalle.setBorder(null);
        btn_agregarDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarDetalleActionPerformed(evt);
            }
        });
        bg_detalles.add(btn_agregarDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 150, 20));

        bg_nuevaFac.add(bg_detalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 640, 280));

        tabla_proyectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id.Proyecto", "Nombre", "Descripción", "Horas Adeudadas", "Saldo Adeudado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla_proyectos);
        if (tabla_proyectos.getColumnModel().getColumnCount() > 0) {
            tabla_proyectos.getColumnModel().getColumn(3).setHeaderValue("Horas Adeudadas");
            tabla_proyectos.getColumnModel().getColumn(4).setHeaderValue("Saldo Adeudado");
        }

        bg_nuevaFac.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 600, 110));

        lbl_nuevaFac.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lbl_nuevaFac.setText("NUEVA FACTURA - CUIT N°: xx-xxxxxxxx-x");
        bg_nuevaFac.add(lbl_nuevaFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        btn_selecProyecto.setBackground(new java.awt.Color(241, 232, 118));
        btn_selecProyecto.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btn_selecProyecto.setText("Seleccionar proyecto");
        btn_selecProyecto.setBorder(null);
        btn_selecProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selecProyectoActionPerformed(evt);
            }
        });
        bg_nuevaFac.add(btn_selecProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 150, 30));

        getContentPane().add(bg_nuevaFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_selecProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selecProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_selecProyectoActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_emitirFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_emitirFacActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_emitirFacActionPerformed

    private void btn_agregarDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarDetalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregarDetalleActionPerformed

    private void txt_hsPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hsPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hsPagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_detalles;
    private javax.swing.JPanel bg_nuevaFac;
    private javax.swing.JButton btn_agregarDetalle;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_emitirFac;
    private javax.swing.JButton btn_selecProyecto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_canths;
    private javax.swing.JLabel lbl_detalleFac;
    private javax.swing.JLabel lbl_nuevaFac;
    private javax.swing.JTable tabla_detallesFac;
    private javax.swing.JTable tabla_proyectos;
    private javax.swing.JTextField txt_hsPagar;
    // End of variables declaration//GEN-END:variables
}
