/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Marisol
 */
public class NuevoEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form NuevoEmpleado
     */
    public NuevoEmpleado() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_legajo = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        lbl_dni = new javax.swing.JLabel();
        lbl_fechNac = new javax.swing.JLabel();
        lbl_apellidos = new javax.swing.JLabel();
        lbl_rol = new javax.swing.JLabel();
        lbl_domicilio = new javax.swing.JLabel();
        lbl_mail = new javax.swing.JLabel();
        lbl_pais = new javax.swing.JLabel();
        lbl_provincia = new javax.swing.JLabel();
        lbl_telefono = new javax.swing.JLabel();
        lbl_localidad1 = new javax.swing.JLabel();
        lbl_codPostal1 = new javax.swing.JLabel();
        txt_legajo = new javax.swing.JTextField();
        txt_dni = new javax.swing.JTextField();
        txt_nombres = new javax.swing.JTextField();
        cb_codpostal = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_apellidos = new javax.swing.JTextField();
        txt_mail = new javax.swing.JTextField();
        txt_rol = new javax.swing.JFormattedTextField();
        txt_fechNac = new javax.swing.JFormattedTextField();
        txt_domicilio = new javax.swing.JTextField();
        cb_localidad = new javax.swing.JComboBox<>();
        cb_provincia = new javax.swing.JComboBox<>();
        cb_pais = new javax.swing.JComboBox<>();
        lbl_fechIng1 = new javax.swing.JLabel();
        txt_fechIng1 = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btn_crearEmpleado = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 232, 118));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setText("NUEVO EMPLEADO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lbl_legajo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbl_legajo.setText("LEGAJO N°");
        jPanel1.add(lbl_legajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        lbl_nombres.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbl_nombres.setText("Nombres");
        jPanel1.add(lbl_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        lbl_dni.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbl_dni.setText("D.N.I. N°");
        jPanel1.add(lbl_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        lbl_fechNac.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbl_fechNac.setText("Fecha de nacimiento");
        jPanel1.add(lbl_fechNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        lbl_apellidos.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbl_apellidos.setText("Apellidos");
        jPanel1.add(lbl_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        lbl_rol.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbl_rol.setText("Rol");
        jPanel1.add(lbl_rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        lbl_domicilio.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbl_domicilio.setText("Domicilio");
        jPanel1.add(lbl_domicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));

        lbl_mail.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbl_mail.setText("Correo electrónico");
        jPanel1.add(lbl_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        lbl_pais.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbl_pais.setText("País");
        jPanel1.add(lbl_pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, -1, -1));

        lbl_provincia.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbl_provincia.setText("Provincia");
        jPanel1.add(lbl_provincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, -1));

        lbl_telefono.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbl_telefono.setText("Teléfono");
        jPanel1.add(lbl_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        lbl_localidad1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbl_localidad1.setText("Localidad");
        jPanel1.add(lbl_localidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        lbl_codPostal1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbl_codPostal1.setText("Código postal");
        jPanel1.add(lbl_codPostal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, -1));

        txt_legajo.setBorder(null);
        txt_legajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_legajoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_legajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 130, 20));

        txt_dni.setBorder(null);
        jPanel1.add(txt_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 130, 20));

        txt_nombres.setBorder(null);
        jPanel1.add(txt_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 200, 20));

        cb_codpostal.setBorder(null);
        jPanel1.add(cb_codpostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 80, 20));

        txt_telefono.setBorder(null);
        jPanel1.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 100, 20));

        txt_apellidos.setBorder(null);
        jPanel1.add(txt_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 200, 20));

        txt_mail.setBorder(null);
        jPanel1.add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 200, 20));

        txt_rol.setBorder(null);
        txt_rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rolActionPerformed(evt);
            }
        });
        jPanel1.add(txt_rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 130, 20));

        txt_fechNac.setBorder(null);
        jPanel1.add(txt_fechNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 130, 20));

        txt_domicilio.setBorder(null);
        jPanel1.add(txt_domicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 320, 20));

        cb_localidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cb_localidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 120, -1));

        cb_provincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cb_provincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 120, -1));

        cb_pais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cb_pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 120, -1));

        lbl_fechIng1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbl_fechIng1.setText("Fecha de ingreso");
        jPanel1.add(lbl_fechIng1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        txt_fechIng1.setBorder(null);
        jPanel1.add(txt_fechIng1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 130, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 172, 340, 10));

        btn_crearEmpleado.setBackground(new java.awt.Color(102, 153, 0));
        btn_crearEmpleado.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_crearEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconCheck.png"))); // NOI18N
        btn_crearEmpleado.setText("Registrar Empleado");
        btn_crearEmpleado.setBorder(null);
        btn_crearEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_crearEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, 190, 40));

        btn_cancelar.setBackground(new java.awt.Color(255, 0, 0));
        btn_cancelar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconCancel.png"))); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setBorder(null);
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_legajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_legajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_legajoActionPerformed

    private void txt_rolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rolActionPerformed

    private void btn_crearEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearEmpleadoActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_crearEmpleadoActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_crearEmpleado;
    private javax.swing.JTextField cb_codpostal;
    private javax.swing.JComboBox<String> cb_localidad;
    private javax.swing.JComboBox<String> cb_pais;
    private javax.swing.JComboBox<String> cb_provincia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_apellidos;
    private javax.swing.JLabel lbl_codPostal1;
    private javax.swing.JLabel lbl_dni;
    private javax.swing.JLabel lbl_domicilio;
    private javax.swing.JLabel lbl_fechIng1;
    private javax.swing.JLabel lbl_fechNac;
    private javax.swing.JLabel lbl_legajo;
    private javax.swing.JLabel lbl_localidad1;
    private javax.swing.JLabel lbl_mail;
    private javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_pais;
    private javax.swing.JLabel lbl_provincia;
    private javax.swing.JLabel lbl_rol;
    private javax.swing.JLabel lbl_telefono;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_dni;
    private javax.swing.JTextField txt_domicilio;
    private javax.swing.JFormattedTextField txt_fechIng1;
    private javax.swing.JFormattedTextField txt_fechNac;
    private javax.swing.JTextField txt_legajo;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_nombres;
    private javax.swing.JFormattedTextField txt_rol;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
