/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Marisol
 */
public class RestablecerContraseña extends javax.swing.JFrame {

    /**
     * Creates new form RestablecerContraseña
     */
    public RestablecerContraseña() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        lbl_logo = new javax.swing.JLabel();
        lbl_restablecer = new javax.swing.JLabel();
        lbl_legajo = new javax.swing.JLabel();
        lbl_mail = new javax.swing.JLabel();
        btn_volverAtras = new javax.swing.JButton();
        txt_legajo = new javax.swing.JTextField();
        txt_mail = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btn_salir = new javax.swing.JButton();
        btn_enviar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo pequeño.png"))); // NOI18N
        background.add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 66));

        lbl_restablecer.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lbl_restablecer.setText("RESTABLECER CONTRASEÑA");
        background.add(lbl_restablecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        lbl_legajo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbl_legajo.setText("Legajo");
        background.add(lbl_legajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        lbl_mail.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbl_mail.setText("Correo Electrónico");
        background.add(lbl_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        btn_volverAtras.setBackground(new java.awt.Color(132, 119, 112));
        btn_volverAtras.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btn_volverAtras.setForeground(new java.awt.Color(255, 255, 255));
        btn_volverAtras.setText("Volver a inicio de sesión");
        btn_volverAtras.setBorder(null);
        btn_volverAtras.setFocusable(false);
        btn_volverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverAtrasActionPerformed(evt);
            }
        });
        background.add(btn_volverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 180, 30));

        txt_legajo.setForeground(new java.awt.Color(153, 153, 153));
        txt_legajo.setText("Ingrese el legajo...");
        txt_legajo.setBorder(null);
        txt_legajo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_legajoMouseClicked(evt);
            }
        });
        txt_legajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_legajoActionPerformed(evt);
            }
        });
        background.add(txt_legajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 170, 30));

        txt_mail.setForeground(new java.awt.Color(153, 153, 153));
        txt_mail.setText("Ingrese la contraseña...");
        txt_mail.setBorder(null);
        background.add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 150, 30));

        jSeparator1.setForeground(new java.awt.Color(243, 234, 232));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 190, 20));

        jSeparator2.setForeground(new java.awt.Color(243, 234, 232));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 190, 20));

        btn_salir.setBackground(new java.awt.Color(255, 255, 255));
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconSalir.png"))); // NOI18N
        btn_salir.setBorder(null);
        btn_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_salir.setFocusable(false);
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        background.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 40, -1));

        btn_enviar1.setBackground(new java.awt.Color(231, 197, 59));
        btn_enviar1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btn_enviar1.setText("Enviar al correo");
        btn_enviar1.setBorder(null);
        btn_enviar1.setFocusable(false);
        btn_enviar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviar1ActionPerformed(evt);
            }
        });
        background.add(btn_enviar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 120, 30));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_legajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_legajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_legajoActionPerformed

    private void btn_volverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverAtrasActionPerformed
        this.dispose();
        InicioSesion view = new InicioSesion();
        view.setVisible(true);
    }//GEN-LAST:event_btn_volverAtrasActionPerformed

    private void txt_legajoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_legajoMouseClicked
       txt_legajo.setText("");
    }//GEN-LAST:event_txt_legajoMouseClicked

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
       this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_enviar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_enviar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestablecerContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestablecerContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestablecerContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestablecerContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestablecerContraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btn_enviar1;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_volverAtras;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_legajo;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_mail;
    private javax.swing.JLabel lbl_restablecer;
    private javax.swing.JTextField txt_legajo;
    private javax.swing.JTextField txt_mail;
    // End of variables declaration//GEN-END:variables
}
