/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JPanel;

/**
 *
 * @author Marisol
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
       
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundMenu = new javax.swing.JPanel();
        lbl_clientes = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_verProyectos = new javax.swing.JButton();
        btn_listarClientes = new javax.swing.JButton();
        lbl_equiposDesarrollo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btn_verEmpleados = new javax.swing.JButton();
        btn_consultarHistorial = new javax.swing.JButton();
        lbl_proyectos = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btn_nuevoCliente = new javax.swing.JButton();
        btn_verEquipos = new javax.swing.JButton();
        lbl_reportes = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        btn_verReportes = new javax.swing.JButton();
        btn_cerrarSesion = new javax.swing.JButton();
        container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundMenu.setBackground(new java.awt.Color(241, 232, 118));
        backgroundMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_clientes.setBackground(new java.awt.Color(39, 18, 7));
        lbl_clientes.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lbl_clientes.setForeground(new java.awt.Color(39, 18, 7));
        lbl_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconCliente.png"))); // NOI18N
        lbl_clientes.setText("Clientes e Historial");
        backgroundMenu.add(lbl_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 21, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(243, 234, 232));
        jSeparator1.setForeground(new java.awt.Color(39, 18, 7));
        backgroundMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 193, 17));

        btn_verProyectos.setBackground(new java.awt.Color(132, 119, 112));
        btn_verProyectos.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_verProyectos.setForeground(new java.awt.Color(255, 255, 255));
        btn_verProyectos.setText("Ver proyectos");
        btn_verProyectos.setBorder(null);
        btn_verProyectos.setFocusable(false);
        btn_verProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verProyectosActionPerformed(evt);
            }
        });
        backgroundMenu.add(btn_verProyectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 240, 30));

        btn_listarClientes.setBackground(new java.awt.Color(132, 119, 112));
        btn_listarClientes.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_listarClientes.setForeground(new java.awt.Color(255, 255, 255));
        btn_listarClientes.setText("Listar Clientes");
        btn_listarClientes.setBorder(null);
        btn_listarClientes.setFocusable(false);
        backgroundMenu.add(btn_listarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 240, 30));

        lbl_equiposDesarrollo.setBackground(new java.awt.Color(39, 18, 7));
        lbl_equiposDesarrollo.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lbl_equiposDesarrollo.setForeground(new java.awt.Color(39, 18, 7));
        lbl_equiposDesarrollo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconEquipo.png"))); // NOI18N
        lbl_equiposDesarrollo.setText("Equipos de desarrollo");
        backgroundMenu.add(lbl_equiposDesarrollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(243, 234, 232));
        jSeparator2.setForeground(new java.awt.Color(39, 18, 7));
        backgroundMenu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 193, 17));

        btn_verEmpleados.setBackground(new java.awt.Color(132, 119, 112));
        btn_verEmpleados.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_verEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        btn_verEmpleados.setText("Ver Empleados");
        btn_verEmpleados.setBorder(null);
        btn_verEmpleados.setFocusable(false);
        btn_verEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verEmpleadosActionPerformed(evt);
            }
        });
        backgroundMenu.add(btn_verEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 240, 30));

        btn_consultarHistorial.setBackground(new java.awt.Color(132, 119, 112));
        btn_consultarHistorial.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_consultarHistorial.setForeground(new java.awt.Color(255, 255, 255));
        btn_consultarHistorial.setText("Consultar Historial");
        btn_consultarHistorial.setBorder(null);
        btn_consultarHistorial.setFocusable(false);
        btn_consultarHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarHistorialActionPerformed(evt);
            }
        });
        backgroundMenu.add(btn_consultarHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 240, 30));

        lbl_proyectos.setBackground(new java.awt.Color(39, 18, 7));
        lbl_proyectos.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lbl_proyectos.setForeground(new java.awt.Color(39, 18, 7));
        lbl_proyectos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconproyecto.png"))); // NOI18N
        lbl_proyectos.setText("Proyectos");
        backgroundMenu.add(lbl_proyectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(243, 234, 232));
        jSeparator3.setForeground(new java.awt.Color(39, 18, 7));
        backgroundMenu.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 193, 17));

        btn_nuevoCliente.setBackground(new java.awt.Color(132, 119, 112));
        btn_nuevoCliente.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_nuevoCliente.setForeground(new java.awt.Color(255, 255, 255));
        btn_nuevoCliente.setText("+ Nuevo cliente");
        btn_nuevoCliente.setBorder(null);
        btn_nuevoCliente.setFocusable(false);
        btn_nuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoClienteActionPerformed(evt);
            }
        });
        backgroundMenu.add(btn_nuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 240, 30));

        btn_verEquipos.setBackground(new java.awt.Color(132, 119, 112));
        btn_verEquipos.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_verEquipos.setForeground(new java.awt.Color(255, 255, 255));
        btn_verEquipos.setText("Ver Equipos");
        btn_verEquipos.setBorder(null);
        btn_verEquipos.setFocusable(false);
        backgroundMenu.add(btn_verEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 240, 30));

        lbl_reportes.setBackground(new java.awt.Color(39, 18, 7));
        lbl_reportes.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lbl_reportes.setForeground(new java.awt.Color(39, 18, 7));
        lbl_reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconReportes.png"))); // NOI18N
        lbl_reportes.setText("Reportes");
        backgroundMenu.add(lbl_reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(243, 234, 232));
        jSeparator4.setForeground(new java.awt.Color(39, 18, 7));
        backgroundMenu.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 193, 17));

        btn_verReportes.setBackground(new java.awt.Color(132, 119, 112));
        btn_verReportes.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_verReportes.setForeground(new java.awt.Color(255, 255, 255));
        btn_verReportes.setText("Ver reportes");
        btn_verReportes.setBorder(null);
        btn_verReportes.setFocusable(false);
        btn_verReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verReportesActionPerformed(evt);
            }
        });
        backgroundMenu.add(btn_verReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 240, 30));

        btn_cerrarSesion.setBackground(new java.awt.Color(255, 102, 102));
        btn_cerrarSesion.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_cerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconcerrarSesion.png"))); // NOI18N
        btn_cerrarSesion.setText("Cerrar Sesión");
        btn_cerrarSesion.setBorder(null);
        btn_cerrarSesion.setFocusable(false);
        btn_cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarSesionActionPerformed(evt);
            }
        });
        backgroundMenu.add(btn_cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 150, 40));

        getContentPane().add(backgroundMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 720));

        container.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                containerAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        container.setLayout(new java.awt.CardLayout());
        getContentPane().add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 870, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void cambiarPanel(JPanel panelActual){
        container.removeAll();
        container.add(panelActual);
        container.repaint();
        container.revalidate();
    }
    
    private void btn_cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarSesionActionPerformed
      /* InicioSesion view = new InicioSesion();
       this.dispose();
       view.setVisible(true);*/
    }//GEN-LAST:event_btn_cerrarSesionActionPerformed

    private void btn_verReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_verReportesActionPerformed

    private void btn_nuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoClienteActionPerformed
        NuevoCliente view = new NuevoCliente();
        view.setVisible(true);
    }//GEN-LAST:event_btn_nuevoClienteActionPerformed

    private void btn_consultarHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarHistorialActionPerformed
        //HistorialCliente view = new HistorialCliente();
       // cambiarPanel(view);
    }//GEN-LAST:event_btn_consultarHistorialActionPerformed

    private void btn_verEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verEmpleadosActionPerformed
       /* ListarEmpleados view = new ListarEmpleados();*/
//        cambiarPanel(view);
    }//GEN-LAST:event_btn_verEmpleadosActionPerformed

    private void btn_verProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verProyectosActionPerformed
        /*ListarProyectos view = new ListarProyectos();*/
//        cambiarPanel(view);
    }//GEN-LAST:event_btn_verProyectosActionPerformed

    private void containerAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_containerAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_containerAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundMenu;
    private javax.swing.JButton btn_cerrarSesion;
    public javax.swing.JButton btn_consultarHistorial;
    public javax.swing.JButton btn_listarClientes;
    public javax.swing.JButton btn_nuevoCliente;
    public javax.swing.JButton btn_verEmpleados;
    public javax.swing.JButton btn_verEquipos;
    public javax.swing.JButton btn_verProyectos;
    public javax.swing.JButton btn_verReportes;
    public javax.swing.JPanel container;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbl_clientes;
    private javax.swing.JLabel lbl_equiposDesarrollo;
    private javax.swing.JLabel lbl_proyectos;
    private javax.swing.JLabel lbl_reportes;
    // End of variables declaration//GEN-END:variables
}
